version: '3.1'

services:
    db:
        # image: mysql
        build: ./infra/
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: test
        ports:
            - '3306:3306'
        volumes:
            - ./infra/db:/docker-entrypoint-initdb.d
            - mysql-volume:/var/lib/mysql
volumes:
    mysql-volume: