default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123456
  host: 127.0.0.1

development:
  <<: *default
  database: test

test:
  <<: *default
  database: test

production:
  <<: *default
  database: test
